# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
loom.platform = forge

# Mod properties
mod_version = 1.0.0
maven_group = cn.ksmcbrigade.vulkan
archives_name = vulkanmod

# Minecraft properties
minecraft_version = 1.20.1

# Dependencies
forge_version = 1.20.1-47.3.0
mixin_version=0.12.11+mixin.0.8.5